41 implement a score system
AdamLesage/R-Type-epitech pull request #109
Opened 2024-10-01 16:36 UTC by BxptisteM

## Changes made

- Added the score system, it handles the  save of the scores and highscores
- It only save the scores of the last 10 games
- It saves the scores in a config file

## Added/updated tests?

- [ ] Yes
- [x] No

2024-10-02 06:24 UTC, AdamLesage requested changes

2024-10-02 06:24 UTC, AdamLesage commented on src/shared/components/PlayerName.hpp
Il existe déjà un component comme ça: Tag.hpp

2024-10-08 19:05 UTC, BxptisteM commented on src/shared/components/PlayerName.hpp
Je l'ai supprimé

2024-10-08 19:07 UTC, Klayni approved these changes

2024-10-08 19:18 UTC, merged