Implementation of a Makefile and refactor of the CMakeLists
AdamLesage/R-Type-epitech pull request #113
Opened 2024-10-02 08:14 UTC by BxptisteM

## Changes made

- Added 2 separate CMakeLists
- 1 for the tests
- 1 for the binaries
- Changed the compilation to not have to put manually the files in it.

## Added/updated tests?

- [ ] Yes
- [x] No

2024-10-02 08:15 UTC, Klayni approved these changes

2024-10-08 06:54 UTC, AdamLesage requested changes

2024-10-08 06:54 UTC, AdamLesage commented on CMakeLists.txt
Pour les shared lib, il faut seulement mettre les fichiers requis pour chaque shared lib au lieu de le faire recursivement
Sinon la compilation va être vraiement trop longue de compiler des fichiers qui ne sont pas nécessaires

2024-10-08 19:06 UTC, Klayni approved these changes

2024-10-08 19:50 UTC, merged