feat(Entities damage system): entities such as players or enemies can…
AdamLesage/R-Type-epitech pull request #134
Opened 2024-10-09 11:55 UTC by AdamLesage

Damage system implemented

## Changes made

Enemies and players can take damages from enemy projectiles

## Added/updated tests?

- [ ] Yes
- [x] No

2024-10-09 12:13 UTC, BxptisteM approved these changes

2024-10-09 15:34 UTC, rchevallier1234 requested changes

2024-10-09 15:34 UTC, rchevallier1234 commented on src/server/systems/Systems.cpp
error on the player take damage

2024-10-10 11:06 UTC, rchevallier1234 approved these changes

2024-10-10 11:34 UTC, Victorhrst approved these changes

2024-10-10 12:10 UTC, mathieu-MZ approved these changes

2024-10-10 12:18 UTC, merged