175 world asset editor
AdamLesage/R-Type-epitech pull request #197
Opened 2024-10-21 15:44 UTC by rchevallier1234

## Changes made

add the asset selector and the drag and drop on the asset editor

## Added/updated tests?

- [x] Yes
- [x] No

2024-10-22 07:16 UTC, AdamLesage requested changes

2024-10-22 07:16 UTC, AdamLesage commented on src/asset_editor/history/Asset.hpp
mettre un brief pour le getGlobalBoounds

2024-10-24 15:16 UTC, Victorhrst approved these changes

2024-10-25 15:27 UTC, BxptisteM approved these changes

2024-10-26 09:20 UTC, Klayni approved these changes

2024-10-28 07:25 UTC, mathieu-MZ approved these changes

2024-10-28 07:25 UTC, merged