232 change protocol parsing for asseteditor
AdamLesage/R-Type-epitech pull request #235
Opened 2024-10-28 15:45 UTC by rchevallier1234

## Changes made

change the parsing protocol to handle scene of asset editor

## Added/updated tests?

- [ ] Yes
- [ ] No,

2024-10-28 15:50 UTC, mathieu-MZ commented on src/client/GameEngine/ProtocolParsing.cpp
Remove debug print such as  std::cout << "message len" << std::endl;

2024-10-29 08:52 UTC, BxptisteM approved these changes

2024-10-29 09:56 UTC, AdamLesage requested changes

2024-10-29 09:56 UTC, AdamLesage commented on src/client/GameEngine/GameEngine.cpp
Ce n'est pas windows pas compatible la déclaration de _protocol parsing, il faut ajouter les separator dans le define

2024-10-29 17:24 UTC, AdamLesage approved these changes

2024-10-29 17:25 UTC, merged