239 implement friendly fire
AdamLesage/R-Type-epitech pull request #245
Opened 2024-10-29 15:37 UTC by mathieu-MZ

## Changes made

Add a friendly fire option in setting and game logic 

## Added/updated tests?

- [x] No

2024-10-29 16:12 UTC, Victorhrst approved these changes
pa ouf

2024-10-29 17:21 UTC, AdamLesage requested changes

2024-10-29 17:21 UTC, AdamLesage commented on src/client/RenderEngine/Scenes/Settings.cpp
Explique pourquoi il y a 9 choix dans la condition ligne 103
C'est incompréhensible pour un nouveau contributeur meme si tu l'expliques dans le fichier hpp

2024-10-29 17:21 UTC, AdamLesage commented on src/client/RenderEngine/Scenes/Settings.cpp
pareil pour la boucle for, a chaque fois tu dois idéalement mettre un commentaire pour chaque if et pour chaque boucle pour expliquer l'utilité du code

2024-10-31 09:40 UTC, AdamLesage requested changes

2024-10-31 09:40 UTC, AdamLesage commented on src/client/AudioEngine/AudioEngine.cpp
Son du lobby mauvais

2024-10-31 10:04 UTC, AdamLesage requested changes

2024-10-31 10:04 UTC, AdamLesage commented on src/client/RenderEngine/Scenes/Settings.hpp
manque un brief pour la fonction display()

2024-10-31 10:08 UTC, AdamLesage requested changes

2024-10-31 10:08 UTC, AdamLesage commented on src/client/RenderEngine/Scenes/Settings.cpp
Paths invalid need to add PATH_SEPARATOR for each path

2024-10-31 10:24 UTC, AdamLesage requested changes

2024-10-31 10:24 UTC, AdamLesage commented on src/client/RenderEngine/Scenes/Settings.hpp
Const char * invalide car cela utilise un pointeur, utilise plutot un const std::string au lieu d'un const char *

2024-10-31 10:24 UTC, AdamLesage commented on src/client/RenderEngine/Scenes/Settings.cpp
Retirer le const char * et utiliser un const std::string à la place pour eviter la manipulation de pointeur direct

2024-10-31 10:38 UTC, Klayni approved these changes

2024-10-31 10:47 UTC, BxptisteM approved these changes
Ok pour moi, je suis du même avis qu'Adam sur les points soulignés

2024-10-31 12:45 UTC, AdamLesage approved these changes

2024-10-31 12:59 UTC, merged