Add Boss system
AdamLesage/R-Type-epitech pull request #262
Opened 2024-11-01 10:59 UTC by Victorhrst

## Changes made

Add the boss with his wave of ennemy

## Added/updated tests?

- [ ] No

2024-11-01 13:11 UTC, BxptisteM approved these changes

2024-11-01 13:23 UTC, AdamLesage requested changes

2024-11-01 13:23 UTC, AdamLesage commented on src/server/GameLogique/GameLogique.cpp
pense à retirer les print de debug avant de faire une PR

2024-11-01 13:23 UTC, AdamLesage commented on src/server/systems/Systems.cpp
fais une autre condition ou change le commentaire de la condition déjà existante car on ne sait pas pourquoi tu mets le "&& bossTakeDamage == false"

2024-11-01 13:23 UTC, AdamLesage commented on src/server/systems/Systems.cpp
Pareil pour toutes les autres conditions, explique ce que tu rajoutes dans la condition dans le commentaire ou fais une autre condition  à part

2024-11-01 13:23 UTC, AdamLesage commented on src/server/systems/Systems.cpp
Il faut retirer le print de debug avec std::cout mais tu peux laisser le debug avec le logger  dans la condition
if (bossTakeDamage && collisionX && collisionY)

2024-11-01 13:23 UTC, AdamLesage commented on src/server/systems/Systems.cpp
Rename la fonction autrement pourvoid Systems::wave1(Registry& reg, std::unique_ptr<NetworkSender>& networkSender, int j), à quoi sert cette fonction ? 
Le nom est pas assez explicite

2024-11-01 13:23 UTC, AdamLesage commented on src/server/systems/Systems.cpp
Pareil pour les fonctions wave2 et wave3

2024-11-01 13:23 UTC, AdamLesage commented on src/server/systems/Systems.cpp
Change le nom de la variable j, on ne sait pas à quoi correspond le j

2024-11-01 13:23 UTC, AdamLesage commented on src/server/systems/Systems.cpp
A quoi sert cette boucle for (int j = 0; j < 5; ++j), on ne sait pas à quoi correspond le 5, essaye de mettre un nom de variable  par exemple

const unsigned int NUMBER_WAVE = 5;
for (int j = 0; j < NUMBER_WAVE; ++j)

On comprendra mieux a quoi cette boucle sert

2024-11-01 13:30 UTC, Victorhrst commented on src/server/systems/Systems.cpp
C'est pas mon code les collisions
J'ai juste réimplémenter le système existant pour les boss cette condition permet de return quand il y a pas de collision 
C'est pour ca que le commentaire dis No collision

2024-11-01 14:04 UTC, AdamLesage approved these changes

2024-11-02 09:43 UTC, mathieu-MZ approved these changes

2024-11-02 12:21 UTC, merged