fix (Sound) fix the bug of the shoot sound
AdamLesage/R-Type-epitech pull request #266
Opened 2024-11-01 17:51 UTC by Victorhrst

## 

Sound of shoot fixed

## Added/updated tests?

- [ ] Yes
- [ ] No

2024-11-01 18:10 UTC, AdamLesage approved these changes

2024-11-01 18:10 UTC, AdamLesage approved these changes

2024-11-02 07:58 UTC, mathieu-MZ approved these changes

2024-11-02 11:05 UTC, BxptisteM approved these changes

2024-11-02 19:59 UTC, Klayni approved these changes

2024-11-02 22:43 UTC, rchevallier1234 requested changes
Ca ne peux pas marcher sa vas crée un décalage car tu na pas ajouter shoot_song a protocol parking.cfg

2024-11-03 13:03 UTC, Victorhrst commented
> Ca ne peux pas marcher sa vas crée un décalage car tu na pas ajouter shoot_song a protocol parsing.cfg

Effectivement je n'avais pas push le fichier cfg

2024-11-03 13:07 UTC, rchevallier1234 approved these changes

2024-11-03 20:18 UTC, merged